version: '3.8'
services:
  fastapi_service:
    build:
      context: ./source/fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./source/fastapi:/app
    restart: always